### ISSUE TITLE
Thanks for doing all of these :-)

### ISSUE THREAD

**Issue by yw662** [alanorth/aur-linux-clear-bin#1]
I have been busy this month and have got no time for things like this. Very much thanks for your help.

there are sth worth noticing though:
* I noticed you added `linux.preset`. In that case you may also want a `hook` for `mkinitcpio`. Although I want to keep initrd optional (since clear kernel is designed for booting as fast as it can), it is up to you how to do it the right way.
* You added fingerprint for the packed tarball. I was not doing this because it is really annoying to do the hashing for big trunks, esp when it need to be downloaded first, and esp when it is expected to be upgraded every week. Again it is up to you.
* It is needed to keep track of the newest version of the kernel and update everything in the package. I planned to write a script to this automatically, but I have done nothing of it right now. You might want to write the script also.

Btw, how would you like me to merge your code, and would you like me to hand over the package to you ?

**Comment by yw662** [comment]
Btw, there is a `header` package for thia kernel, which is at AUR:clear-linux-headers-bin. It is bettrr to do the same thing there as well, if you have time for it.

**Comment by alanorth** [comment]
> I noticed you added linux.preset. In that case you may also want a hook for mkinitcpio. Although I want to keep initrd optional (since clear kernel is designed for booting as fast as it can), it is up to you how to do it the right way.

Yeah I've added hooks for `mkinitcpio` now, so the initramfs is regenerated or removed if the package is updated or removed. Regarding the initrd, I'm personally interested in running an Arch Linux system with a kernel that has the Clear Linux patches, but without having to compile `linux-clear` from AUR a few times a week. In that vein I am trying to essentially make this package the binary version of `linux-clear`. My system uses dm-crypt and it's much easier to boot if that and some other modules are just in the initrd (also i915, ext4, and hid-apple).

> You added fingerprint for the packed tarball. I was not doing this because it is really annoying to do the hashing for big trunks, esp when it need to be downloaded first, and esp when it is expected to be upgraded every week. Again it is up to you.

I don't mind—it's the Arch way after all! And AUR users are power users anyways.

> It is needed to keep track of the newest version of the kernel and update everything in the package. I planned to write a script to this automatically, but I have done nothing of it right now. You might want to write the script also.

Ah, you mean to find the latest Clear version (ie, 30820), get its manifest, find the kernel, etc? Yeah, kinda annoying. I had to study you PKGBUILD to figure out how it works! Do they publish new Clear versions somewhere? I found this page: https://clearlinux.org/node/15538

> Btw, how would you like me to merge your code, and would you like me to hand over the package to you ?

Sure, you can give it to me, that is, if you don't mind me bringing it closer to the `linux-clear`. I will keep working on it for my own purposes in the short term at least.

> Btw, there is a header package for this kernel, which is at AUR:linux-clear-headers-bin. It is better to do the same thing there as well, if you have time for it.

I saw that. Good work. It does need a little love as well. I didn't fix that one yet because I'm not building any kernel modules with DKMS now that Linux Clear includes WireGuard.

**Comment by yw662** [comment]
The version of latest clear version can be found here:
https://cdn.download.clearlinux.org/current/latest

I am glad you would like to take over it. Would you like to take over the
header package as well?

Besides there is another package containing i915 firmware which is shipped
with clear linux. It is at intel-ucode-clear. You might be interested with
it as well.

>
>

**Comment by alanorth** [comment]
Sure I can take over `linux-clear-bin` and maybe `linux-clear-headers-bin`, though I won't have time to test the headers package for a few days.

BTW I was referring to the i915 kernel module used for [early kernel mode setting on Arch](https://wiki.archlinux.org/index.php/Kernel_mode_setting#Early_KMS_start), not the firmware. Speaking of firmware, I'm wondering what the difference between Clear Linux's `intel-ucode-clear` and Arch's [intel-ucode](https://www.archlinux.org/packages/extra/any/intel-ucode/) is... is Clear's newer?

**Comment by alanorth** [comment]
Hey @yw662 I saw you transferred maintainership of the package to me on AUR. Thanks. I'm having an issue pushing to AUR due to something in the git history:

```
$ git push origin                                                                        
Enumerating objects: 19, done.                                                                                                                  
Counting objects: 100% (19/19), done.                                                                                                           
Delta compression using up to 4 threads                                                                                                         
Compressing objects: 100% (9/9), done.                                  
Writing objects: 100% (17/17), 6.82 KiB | 6.82 MiB/s, done.             
Total 17 (delta 9), reused 14 (delta 8)                                                                                                         
remote: error: The following error occurred when parsing commit                                                                                 
remote: error: 6525bac549b484bf7987c59d30221239c2146a8d:                
remote: error: missing source file: depmod.hook                                                                                                 
remote: error: hook declined to update refs/heads/master                                                                                        
To ssh://aur.archlinux.org/linux-clear-bin.git                                                                                                  
 ! [remote rejected] master -> master (hook declined)                                                                                           
error: failed to push some refs to 'ssh://aur@aur.archlinux.org/linux-clear-bin.git'
```

It seems I forgot to update the `.SRCINFO` file when I moved the depmod hook and now I've gotta go back and fix the history... and there's no force push. Grrrr. I will do it when I get time...

**Comment by alanorth** [comment]
I spent some time going back in git history and fixing the `.SRCINFO` where depmod.hook was erroneously still present, but after a few rounds of rebasing and merging the AUR kept complaining about some other commit. I decided it was just easier to squash all my commits and that worked. It's not optimal, but at least I preserved all my nice git commit messages. :)

Cheers!
